CREATE DATABASE BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;
CREATE TABLE IF NOT EXISTS ARTISTA (
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (255) NOT NULL,
    FOTO BLOB NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS GENERO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR (255) NOT NULL
);
CREATE TABLE IF NOT EXISTS ALBUM (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR (255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    CAPA BLOB NOT NULL,
    NOME VARCHAR (255) NOT NULL,
    QTD_MUSICA INTEGER NOT NULL,
    FK_ARTISTA_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS FAIXA (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LETRA VARCHAR(255) NOT NULL,
    DURACAO VARCHAR(60) NOT NULL,
    CAPA BLOB NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FK_GENERO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID) ON DELETE CASCADE,
    FK_ALBUM_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID) ON DELETE CASCADE
);