CREATE DATABASE BD_AGENDA_MEDICA;
USE BD_AGENDA_MEDICA;
CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(14) NOT NULL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PROBLEMA_SAÚDE VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS MEDICO(
	CPF VARCHAR(14) NOT NULL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    FORMACAO VARCHAR(255) NOT NULL,
    RG VARCHAR(8) NOT NULL
);
CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_CONSULTA DATE NOT NULL,
    FK_PACIENTE_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_PACIENTE_CPF) REFERENCES PACIENTE(CPF) ON DELETE CASCADE,
    FK_MEDICO_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_MEDICO_CPF) REFERENCES MEDICO(CPF) ON DELETE CASCADE
);