CREATE DATABASE BD_BIBLIOTECA_DIGITAL;
USE BD_BIBLIOTECA_DIGITAL;
CREATE TABLE IF NOT EXISTS AUTOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    PRECO DOUBLE NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    AVALIACAO VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS LEITOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS LIVRO_LEITOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	FK_LIVRO_DIGITAL_ID INTEGER NOT NULL,
    FOREIGN KEY(FK_LIVRO_DIGITAL_ID) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE,
    FK_LEITOR_ID INTEGER NOT NULL,
    FOREIGN KEY( FK_LEITOR_ID) REFERENCES LEITOR(ID) ON DELETE CASCADE
);