CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;
CREATE TABLE IF NOT EXISTS USUARIOS(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR (500),
    USU_PROFISSAO VARCHAR (200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORSIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR (2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MÉDIO","SUPERIOR"),
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);
CREATE TABLE IF NOT EXISTS ENQUETES(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DATA_FINAL DATE NOT NULL,
    ENQ_DECRICAO VARCHAR (255) NOT NULL,
    ENQ_NOME VARCHAR (255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIOS(USU_CODIGO) ON DELETE CASCADE,
    PRIMARY KEY (ENQ_CODIGO)
);
CREATE TABLE IF NOT EXISTS USUARIOS_RESPONDE_ENQUETES(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIOS(USU_CODIGO) ON DELETE CASCADE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETES(ENQ_CODIGO) ON DELETE CASCADE,
    PRIMARY KEY (URE_CODIGO)
);
CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DECRICAO VARCHAR (255) UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETES(ENQ_CODIGO) ON DELETE CASCADE,
    PRIMARY KEY (PER_CODIGO)
);
CREATE TABLE IF NOT EXISTS RESPOSTAS(
    RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DECRICAO VARCHAR (255) UNIQUE,
    RES_CERTA VARCHAR (1),
    FK_PER_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE,
    PRIMARY KEY (RES_CODIGO)
);
INSERT INTO USUARIOS(	USU_DATA_CADASTRO,
						USU_LOGIN,
                        USU_AREA_ATUACAO,
                        USU_PROFISSAO,
                        USU_AREA_FORMACAO,
                        USU_DATANASC,
                        USU_ESTADO_CIVIL,
                        USU_ESTADO,
                        USU_ESCOLARIDADE,
                        USU_EMAIL,
                        USU_SENHA,
                        USU_NOME)
VALUES ("2025-10-01","MATHEUS","DESENVOLVEDOR DE SISTEMAS","PROGRAMADOR","Ciências Exatas","2008-08-02","SOLTEIRO","SP","MÉDIO","matheus@gmail.com","Ma1070303","MATHEUS");
INSERT INTO USUARIOS(	USU_DATA_CADASTRO,
						USU_LOGIN,
                        USU_AREA_ATUACAO,
                        USU_PROFISSAO,
                        USU_AREA_FORMACAO,
                        USU_DATANASC,
                        USU_ESTADO_CIVIL,
                        USU_ESTADO,
                        USU_ESCOLARIDADE,
                        USU_EMAIL,
                        USU_SENHA,
                        USU_NOME)
VALUES ("2025-10-01","NERI","DESENVOLVEDOR DE SISTEMAS","PROGRAMADOR","Ciências Exatas","2008-08-02","SOLTEIRO","RJ","MÉDIO","NERI@gmail.com","Ne1070303","NERI");
INSERT INTO USUARIOS(	USU_DATA_CADASTRO,
						USU_LOGIN,
                        USU_AREA_ATUACAO,
                        USU_PROFISSAO,
                        USU_AREA_FORMACAO,
                        USU_DATANASC,
                        USU_ESTADO_CIVIL,
                        USU_ESTADO,
                        USU_ESCOLARIDADE,
                        USU_EMAIL,
                        USU_SENHA,
                        USU_NOME)
VALUES ("2025-10-01","HENRIQUE","DESENVOLVEDOR DE SISTEMAS","PROGRAMADOR","Ciências Exatas","2008-08-02","SOLTEIRO","MG","SUPERIOR","HENRIQUE@gmail.com","He1070303","HENRIQUE");
INSERT INTO ENQUETES(	ENQ_DATA_INICIAL,
                        ENQ_DATA_FINAL,
                        ENQ_DECRICAO,
                        ENQ_NOME,
                        FK_USU_CODIGO)
VALUES ("2025-09-01","2025-10-01","DÁ PRA FAZER VITAMINA DE BANANA SEM A BANANA?","PERGUNTA 1",1);
INSERT INTO ENQUETES(	ENQ_DATA_INICIAL,
                        ENQ_DATA_FINAL,
                        ENQ_DECRICAO,
                        ENQ_NOME,
                        FK_USU_CODIGO)
VALUES ("2025-09-01","2025-10-01","COMO CRIARAM A RODA SE NEM TINHA RODA?","PERGUNTA 2",2);
INSERT INTO ENQUETES(	ENQ_DATA_INICIAL,
                        ENQ_DATA_FINAL,
                        ENQ_DECRICAO,
                        ENQ_NOME,
                        FK_USU_CODIGO)
VALUES ("2025-09-01","2025-10-01","Existe moto porta 4 portas?","PERGUNTA 3",3);
INSERT INTO USUARIOS_RESPONDE_ENQUETES(URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-09-01",1,1);
INSERT INTO USUARIOS_RESPONDE_ENQUETES(URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-09-01",2,2);
INSERT INTO USUARIOS_RESPONDE_ENQUETES(URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-09-01",3,3);
INSERT INTO PERGUNTAS(PER_DECRICAO, FK_ENQ_CODIGO)
VALUES ("DÁ PRA FAZER VITAMINA DE BANANA SEM A BANANA?", 1);
INSERT INTO PERGUNTAS(PER_DECRICAO, FK_ENQ_CODIGO)
VALUES ("COMO CRIARAM A RODA SE NEM TINHA RODA?", 2);
INSERT INTO PERGUNTAS(PER_DECRICAO, FK_ENQ_CODIGO)
VALUES ("Existe moto porta 4 portas?", 3);
INSERT INTO RESPOSTAS(RES_DECRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("Fechada","A",1);
INSERT INTO RESPOSTAS(RES_DECRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("Aberta","B",2);
INSERT INTO RESPOSTAS(RES_DECRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("Fechada2","C",3);
SELECT * FROM USUARIOS;
SELECT * FROM ENQUETES;
SELECT * FROM USUARIOS_RESPONDE_ENQUETES;
SELECT * FROM PERGUNTAS;
SELECT * FROM RESPOSTAS;