CREATE DATABASE BD_ESTOQUE_SUPERMERCADO;
USE BD_ESTOQUE_SUPERMERCADO;
CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (255) NOT NULL,
    NOME VARCHAR (255) NOT NULL,
    FOTO BLOB
);
CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (255) NOT NULL,
    ENDERECO VARCHAR (255) NOT NULL
);
CREATE TABLE IF NOT EXISTS PRODUTOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALIDADE DATE,
    QTD INTEGER NOT NULL,
    COR VARCHAR (255) NOT NULL,
    VALOR VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (255) NOT NULL,
    FK_CATEGORIA_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS FORNECEDOR_PRODUTOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_FORNECEDOR_CNPJ VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE,
    FK_PRODUTOS_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_PRODUTOS_ID) REFERENCES PRODUTOS(ID) ON DELETE CASCADE
);