CREATE DATABASE BD_GERENCIAMENTO_PROJETOS;
USE BD_GERENCIAMENTO_PROJETOS;
CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    PRAZO DATE NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VALOR VARCHAR(255) NOT NULL
    );
CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL,
    FUNCAO VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FUNCAO VARCHAR(255) NOT NULL,
    OBJETIVO VARCHAR(255) NOT NULL,
    PRAZO DATE NOT NULL,
	FK_PROJETO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_PROJETO_ID) REFERENCES PROJETO(ID) ON DELETE CASCADE,
    FK_FUNCIONARIO_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);