CREATE DATABASE BD_LOCADORA;
USE BD_LOCADORA;
CREATE TABLE IF NOT EXISTS CLIENT(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);
CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID_CLIENTE INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID_CLIENTE) REFERENCES CLIENTE(CLIENTE_ID),
    KF_PRODUTO_ID_PRODUTO INTEGER NOT NULL,
    FOREIGN KEY (KF_PRODUTO_ID_PRODUTO) REFERENCES PRODUTO(PRODUTO_ID)
);
