CREATE DATABASE BD_RESERVA_HOTEL;
USE BD_RESERVA_HOTEL;
CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(255) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO INTEGER(255) NOT NULL,
    FOTO BLOB NOT NULL,
    VALOR DOUBLE NOT NULL
);
CREATE TABLE IF NOT EXISTS QUARTO_HOSPEDE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_HOSPEDE_CPF VARCHAR(255) NOT NULL,
    FOREIGN KEY(FK_HOSPEDE_CPF) REFERENCES HOSPEDE(CPF) ON DELETE CASCADE,
    FK_QUARTO_ID INTEGER NOT NULL,
    FOREIGN KEY(FK_QUARTO_ID) REFERENCES QUARTO(ID) ON DELETE CASCADE
);
