CREATE DATABASE BD_RESERVA_PASSAGENS_AÉREAS;
USE BD_RESERVA_PASSAGENS_AÉREAS;
CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    COMPANHIA VARCHAR(250) NOT NULL,
    DESTINO VARCHAR(250) NOT NULL,
    DATA_VOO DATE NOT NULL,
    QTD_ASSENTOS INTEGER(255) NOT NULL,
    QTD_PASSAGEIROS INTEGER(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(250) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    PASSAPORTE VARCHAR(250) NOT NULL,
    TELEFONE VARCHAR(250) NOT NULL
);
CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOCALIZACAO VARCHAR(250) NOT NULL,
    CLASSE VARCHAR(250) NOT NULL,
    CUSTO VARCHAR(250) NOT NULL,
	FK_VOO_ID  INTEGER NOT NULL,
    FOREIGN KEY (FK_VOO_ID) REFERENCES VOO(ID) ON DELETE CASCADE,
    FK_PASSAGEIRO_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_PASSAGEIRO_CPF) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE
);