CREATE DATABASE BD_LOCADORA;
USE BD_LOCADORA;
CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);
CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID_CLIENTE INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID_CLIENTE) REFERENCES CLIENTE(CLIENTE_ID),
    KF_PRODUTO_ID_PRODUTO INTEGER NOT NULL,
    FOREIGN KEY (KF_PRODUTO_ID_PRODUTO) REFERENCES PRODUTO(PRODUTO_ID)
);
-- DML-LINGUAGEM DE MANIPULAÇÃO
-- INSERT-INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("EMAIL@EMAIL.COM","19999999999","123456789","LEO");
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("MATHEUS.H.FERREIRA13@ALUNO.SENAI.BR","19993151477","44621350838","MATHEUS");
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("GABRIEL","GABRIEL.COM","0987654321","123456789");
-- SELECT-SELECIONAR
SELECT * FROM CLIENTE;
-- UPDATE-ATUALIZAR

-- DROP-DELETAR
