CREATE DATABASE BD_STREAMING_VIDEO;
USE BD_STREAMING_VIDEO;
CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DECRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_LANCAMENTO DATE NOT NULL,
    AUTOR VARCHAR(255) NOT NULL,
    DURACAO VARCHAR(255) NOT NULL,
    FK_CATEGORIA_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS VISUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QTD VARCHAR(255) NOT NULL,
    FK_VIDEO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_VIDEO_ID) REFERENCES VIDEO(ID) ON DELETE CASCADE
);