Use BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDOR;
INSERT INTO SUPERMERCADO(	SUP_CNPJ, 
							SUP_RAZAO_$OCIAL,
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES ("2131212","Grick",
		"(11) 234265",
		"grick@gmail.com",
		"Grick de tambaú",
		"9999",
		"Tambaú",
		"SP");
INSERT INTO SUPERMERCADO(	SUP_CNPJ, 
							SUP_RAZAO_$OCIAL,
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES ("12.345.678", 
		"Supermercado Bom Preço LTDA",
		"(11) 3456-7890",
		"contato@bompreco.com.br",
		"Avenida Paulista",
		"1000",
		"São Paulo",
		"SP");
INSERT INTO SUPERMERCADO(	SUP_CNPJ, 
							SUP_RAZAO_$OCIAL,
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES ("98.765.432", 
		"Supermercado Pão de Ouro SA",
		"(21) 2345-6789",
		"atendimento@paodeouro.com.br",
		"Rua das Laranjeiras",
		"250",
		"Rio de Janeiro",
		"RJ");
INSERT INTO SUPERMERCADO(	SUP_CNPJ, 
							SUP_RAZAO_$OCIAL,
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES ("56.789.123", 
		"Supermercado Econômico ME",
		"(31) 9876-5432",
		"economico@super.com.br",
		"Avenida Afonso Pena",
		"3000",
		"Belo Horizonte",
		"MG");
INSERT INTO SUPERMERCADO(	SUP_CNPJ, 
							SUP_RAZAO_$OCIAL,
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES ("11.222.333", 
		"Supermercado Verde Vida EIRELI",
		"(41) 4002-8922",
		"verdevida@supermercado.com",
		"Rua XV de Novembro",
		"150",
		"Curitiba",
		"PR");

INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QTD,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES ("7894900010015",
		"Arroz Branco Tipo 1 5kg",
		"5.000g",
		"200",
		"24.90",
		"2026-05-15");
INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QTD,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES ("7891000051234",
		"Feijão Carioca 1kg",
		"1.000g",
		"350",
		"7.50",
		"2026-02-28");
INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QTD,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES ("7898095298765",
		"Leite Integral 1L",
		"1.000ml",
		"500",
		"4.20",
		"2025-11-20");
INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QTD,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES ("7891234567890",
		"Café Torrado e Moído 500g",
		"500g",
		"120",
		"12.90",
		"2026-03-10");
INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QTD,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES ("7896543210987",
		"Biscoito Recheado Chocolate 140g",
		"140g",
		"1000",
		"3.50",
		"2025-12-05");

INSERT INTO CONSUMIDOR(	CON_CPF,
						CON_NOME,
						CON_TELEFONE,
						CON_EMAIL)
VALUES ("123.456.789-09",
		"Ana Beatriz Souza",
		"(11) 91234-5678",
		"ana.souza@gmail.com");
INSERT INTO CONSUMIDOR(	CON_CPF,
						CON_NOME,
						CON_TELEFONE,
						CON_EMAIL)
VALUES ("987.654.321-00",
		"João Pedro Almeida",
		"(21) 99876-5432",
		"joao.almeida@hotmail.com");
INSERT INTO CONSUMIDOR(	CON_CPF,
						CON_NOME,
						CON_TELEFONE,
						CON_EMAIL)
VALUES ("456.789.123-55",
		"Mariana Oliveira",
		"(31) 98877-6655",
		"mariana.oli@yahoo.com");
INSERT INTO CONSUMIDOR(	CON_CPF,
						CON_NOME,
						CON_TELEFONE,
						CON_EMAIL)
VALUES ("321.654.987-22",
		"Lucas Gabriel Fernandes",
		"(41) 97777-8888",
		"lucas.g.fernandes@outlook.com");
INSERT INTO CONSUMIDOR(	CON_CPF,
						CON_NOME,
						CON_TELEFONE,
						CON_EMAIL)
VALUES ("159.753.486-01",
		"Camila Ribeiro Costa",
		"(51) 93456-7890",
		"camila.r.costa@gmail.com");

INSERT INTO FUNCIONARIO(	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASCIMENTO,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES ("123.456.789-10",
		"Paulo Henrique Santos",
		"1990-05-12",
		"(11) 98877-6655",
		"paulo.santos@bompreco.com",
		"CTPS123456-SP",
		"341-1234",
		"456789-0",
		"2022-03-01",
		"44h semanais",
		"12.345.678");
INSERT INTO FUNCIONARIO(	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASCIMENTO,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES ("987.654.321-11",
		"Fernanda Oliveira",
		"1995-08-20",
		"(21) 97777-8888",
		"fernanda.oliveira@paodeouro.com",
		"CTPS654321-RJ",
		"001-2222",
		"112233-1",
		"2021-07-15",
		"40h semanais",
		"98.765.432");
INSERT INTO FUNCIONARIO(	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASCIMENTO,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES ("456.789.123-22",
		"Rafael Gomes",
		"1988-11-03",
		"(31) 96666-5544",
		"rafael.gomes@economico.com",
		"CTPS987654-MG",
		"104-3333",
		"998877-2",
		"2020-01-10",
		"36h semanais",
		"56.789.123");
INSERT INTO FUNCIONARIO(	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASCIMENTO,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES ("321.654.987-33",
		"Ana Carolina Souza",
		"1992-02-28",
		"(41) 95555-4433",
		"ana.souza@verdevida.com",
		"CTPS112233-PR",
		"237-4444",
		"334455-3",
		"2023-05-22",
		"44h semanais",
		"11.222.333");
INSERT INTO FUNCIONARIO(	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASCIMENTO,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES ("159.753.486-44",
		"Juliana Ribeiro",
		"1998-09-15",
		"(31) 91234-5566",
		"juliana.ribeiro@economico.com",
		"CTPS445566-MG",
		"033-5555",
		"667788-4",
		"2024-01-08",
		"30h semanais",
		"56.789.123");

INSERT INTO SUPERMERCADO_PRODUTO(	FK_SUP_CNPJ,
									FK_PRO_ID)
VALUES ("12.345.678",
		"1");
INSERT INTO SUPERMERCADO_PRODUTO(	FK_SUP_CNPJ,
									FK_PRO_ID)
VALUES ("98.765.432",
		"2");
INSERT INTO SUPERMERCADO_PRODUTO(	FK_SUP_CNPJ,
									FK_PRO_ID)
VALUES ("56.789.123", 
		"3");
INSERT INTO SUPERMERCADO_PRODUTO(	FK_SUP_CNPJ,
									FK_PRO_ID)
VALUES ("11.222.333",
		"4");
INSERT INTO SUPERMERCADO_PRODUTO(	FK_SUP_CNPJ,
									FK_PRO_ID)
VALUES ("12.345.678",
		"5");

INSERT INTO PRODUTO_CONSUMIDOR(	FK_CON_CPF,
								FK_PRO_ID)
VALUES ("123.456.789-09", 
		"1");
INSERT INTO PRODUTO_CONSUMIDOR(	FK_CON_CPF,
								FK_PRO_ID)
VALUES ("987.654.321-00", 
		"3");
INSERT INTO PRODUTO_CONSUMIDOR(	FK_CON_CPF,
								FK_PRO_ID)
VALUES ("456.789.123-55",  
		"5");
INSERT INTO PRODUTO_CONSUMIDOR(	FK_CON_CPF,
								FK_PRO_ID)
VALUES ("321.654.987-22", 
		"2");
INSERT INTO PRODUTO_CONSUMIDOR(	FK_CON_CPF,
								FK_PRO_ID)
VALUES ("159.753.486-01",  
		"4");
SELECT * FROM SUPERMERCADO;
SELECT * FROM PRODUTO;
SELECT * FROM CONSUMIDOR;
SELECT * FROM FUNCIONARIO;
SELECT * FROM SUPERMERCADO_PRODUTO;
SELECT * FROM PRODUTO_CONSUMIDOR;
/*
COSULTAR O AUMENTO DE R$ 2,00 NO PREÇO DOS PRODUTOS COM PREÇO ATUAL ACIMA DE 5,00
*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO + 2),2) AS "PREÇO COM AJUSTE DE R$2,00"
FROM 	PRODUTO
WHERE PRO_PRECO >=5;
/*
COSULTAR REDUÇÃO DE R$ 1,00 NO PREÇO DOS PRODUTOS COM PREÇO ATUAL A BAIXO DE 5,00
*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO - 1),2) AS "PREÇO COM REDUÇÃO DE R$1,00"
FROM 	PRODUTO
WHERE PRO_PRECO <5;
/*
COSULTAR COMO SERIA APLICAR UM DESCONTO DE 10% NO PREÇO DE TODOS OS PRODUTOS
*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO - (PRO_PRECO/10)),2) AS "PREÇO COM REDUÇÃO DE R$1,00"
FROM 	PRODUTO;
/*
AJUSTAR O ESTOQUE DO 1° PRODUTO, DIVIDIDO PELA METADE
*/
SELECT 	PRO_ID,
		PRO_NOME,
		PRO_CODIGO_BARRAS,
        PRO_QTD
FROM 	PRODUTO;
UPDATE PRODUTO
SET PRO_QTD = PRO_QTD/2
WHERE PRO_ID=1;
/*CONSULTAR TODOS OS PRODUTOS QUE POSSUEM DATA DE VALIDADE ENTRE SETEMBRO DE 2025 E DEZEMBRO DE 2025*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
		PRO_DATA_VALIDADE AS "DATA DE VALIDADE"
FROM PRODUTO
WHERE PRO_DATA_VALIDADE BETWEEN "2025-09-01" AND "2025-12-31";
/*CONSULTAR TODOS OS PRODUTOS QUE TENHAM PREÇO MAIOR QUE R$10,00 OU MENOR QUE R$4,00*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
		PRO_PRECO AS "PREÇO"
FROM PRODUTO
WHERE PRO_PRECO>=10 OR PRO_PRECO<=4;
/*CONSULTAR OS DDD'S E TELEFONES DOS CONSUMIDORES SEPARADAMENTE*/
SELECT 	CON_NOME AS "NOME DO CONSUMIDOR",
		CON_CPF AS "CPF DO CONSUMIDOR",
        SUBSTRING(CON_TELEFONE, 2,2) AS "DDD DO TELEFONE",
        SUBSTRING(CON_TELEFONE, 5,11) AS "NÚMERO DO TELEFONE"
FROM CONSUMIDOR;
/*GERAR UMA FRASE CONCATENANDO: RAZÃO SOCIAL, CNPJ, TELEFONE E EMAIL*/
SELECT CONCAT ("RAZÃO SOCIAL: ", SUP_RAZAO_$OCIAL)
FROM SUPERMERCADO;
SELECT CONCAT ("CNPJ: ", SUP_CNPJ)
FROM SUPERMERCADO;
SELECT CONCAT ("TELEFONE: ", SUP_TELEFONE)
FROM SUPERMERCADO;
SELECT CONCAT ("EMAIL: ", SUP_EMAIL)
FROM SUPERMERCADO;
SELECT 	CONCAT ("RAZÃO SOCIAL: ", SUP_RAZAO_$OCIAL, 
		CONCAT(" | CNPJ: ", SUP_CNPJ, 
		CONCAT(" | TELEFONE: ", SUP_TELEFONE, 
		CONCAT(" | EMAIL: ", SUP_EMAIL)))) AS FRASE
FROM SUPERMERCADO;
/*GERAR UMA CONSULTA QUE VERIFICA O STATUS DO ESTOQUE DOS PRODUTOS. REGRAS:
1°:QTD<=25: ESTOQUE BAIXO
2°:QTD>25 E QTD<=100:ESTOQUE MÉDIO
3°:QTD:>100:ESTOQUE ALTO*/
SELECT 	PRO_NOME AS "NOME DO PRODUTO",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_QTD AS "QUANTIDADE",
		CASE 
			WHEN PRO_QTD <= 25 THEN "ESTOQUE BAIXO"
            WHEN PRO_QTD > 25 AND PRO_QTD <= 100 THEN "ESTOQUE MÉDIO"
            WHEN PRO_QTD > 100 THEN "ESTOQUE ALTO"
		END AS "NÍVEL DE ESTOQUE"
FROM PRODUTO;
/*GERAR UMA CONSULTA QUE VERIFICA O PESO DOS PRODUTOS. REGRAS:
1°:PESO<=5: PESO BAIXO
2°:PESO>5 E PESO<=50:PESO MÉDIO
3°:PESO:>50:PESO ALTO*/
SELECT 	PRO_NOME AS "NOME DO PRODUTO",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PESO AS "QUANTIDADE",
		CASE 
			WHEN PRO_PESO <= 5 THEN "PESO BAIXO"
            WHEN PRO_PESO > 5 AND PRO_PESO <= 50 THEN "PESO MÉDIO"
            WHEN PRO_PESO > 50 THEN "PESO ALTO"
		END AS "PESO"
FROM PRODUTO;
/*CONTAR QUANTOS CONSUMIDORES TEMOS CADASTRADOS*/
SELECT COUNT(*)
FROM CONSUMIDOR;
SELECT COUNT(*)
FROM SUPERMERCADO;
SELECT COUNT(*)
FROM FUNCIONARIO;
/*SOMAR O PREÇO TOTAL DE TODOS OS PRODUTOS CADASTRADOS*/
SELECT SUM(PRO_PRECO)
FROM PRODUTO;
SELECT CONCAT("R$ ", TRUNCATE (SUM(PRO_PRECO),2)) AS "SOMA TOTAL"
FROM PRODUTO;
/*CALCULAR A MÉDIA DE PREÇOS DOS PRODUTOS*/
SELECT AVG(PRO_PRECO)
FROM PRODUTO;
SELECT CONCAT("R$ ", TRUNCATE (AVG(PRO_PRECO),2)) AS "MÉDIA DE PREÇO"
FROM PRODUTO;
/*SELECIONAR O PRODUTO MAIS CARO*/
SELECT MAX(PRO_PRECO)
FROM PRODUTO;
/*SELECIONAR O ESTOQUE COM MAIOR QTD*/
SELECT MAX(PRO_QTD)
FROM PRODUTO;
/*SELECIONAR O PRODUTO MAIS BARATO*/
SELECT MIN(PRO_PRECO)
FROM PRODUTO;
/*SELECIONAR O ESTOQUE COM MENOR QTD*/
SELECT MIN(PRO_QTD)
FROM PRODUTO;
/*SELECIONAR A DATA E HORA ATUAL*/
SELECT 	NOW() FROM DUAL;
SELECT 	FUN_NOME AS "NOME DO FUNCIONÁRIO",
		DATE_FORMAT(FUN_DATA_NASCIMENTO,"%d/%m/%y") AS "DATA DE NASCIMENTO",
        TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO, NOW()) AS "IDADE"
FROM FUNCIONARIO;

/*FUNÇÕES MATEMÁTICAS
ABS- MÓDULO
ROUND-ARREDONDADOR
POWER-POTÊNCIA*/
SELECT 	ABS(-10),
		ROUND(PRO_PRECO) AS "PREÇO ARREDONDADO",
		POWER(PRO_PRECO,2) AS "PREÇO ELEVADO AO QUADRADO"
FROM PRODUTO;
/*UPPER, LOWER, TRIM*/
SELECT 	UPPER(FUN_NOME) AS "MAIÚSCULAS",
		LOWER(FUN_NOME) AS "MINÚSCULAS",
        TRIM("     MATHEUS") AS "TIRANDO ESPAÇOS"
FROM FUNCIONARIO;
/*GROUP BY*/
SELECT PRO_QTD ,
COUNT(*) AS "REPETIÇÕES"
FROM PRODUTO
GROUP BY PRO_QTD;
/*UNION*/
SELECT FUN_NOME,
		FUN_CPF
FROM FUNCIONARIO
UNION
SELECT FUN_NOME,
		FUN_CPF
FROM FUNCIONARIO;
SELECT * FROM PRODUTO; 
SELECT PRO_NOME 
FROM PRODUTO
UNION ALL
SELECT "Arroz Branco Tipo 1 5kg"
FROM DUAL
UNION ALL
SELECT "Feijão Carioca 1kg"
FROM DUAL;
/*SELECT COM WHERE*/
SELECT	 FUN_NOME AS "NOME",
		FUN_CPF AS "CPF",
        FUN_DATA_NASCIMENTO AS "DATA DE NASCIMENTO",
        TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO,NOW()) AS "IDADE"
FROM FUNCIONARIO
WHERE TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO,NOW()) >=25
AND TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO,NOW())<=35;
/*RETORNAR OS FUNCIONARIOS, CONSUMIDORES E SUPERMERCADOS COM EMAIL = HOTMAIL OU OUTLOOK*/
SELECT 	CON_NOME AS "NOME CONSUMIDOR",
		CON_CPF AS "CPF/CNPJ CONSUMIDOR",
        CON_TELEFONE AS "TELEFONE CONSUMIDOR",
        CON_EMAIL AS "EMAIL CONSUMIDOR",
        "CONSUMIDOR" AS "TIPO"
FROM CONSUMIDOR
WHERE UPPER(CON_EMAIL) LIKE "%%HOTMAIL%%"
OR UPPER(CON_EMAIL) LIKE "%%OUTLOOK%%"
UNION
SELECT 	FUN_NOME AS "NOME FUNCIONÁRIO",
		FUN_CPF AS "CPF/CNPJ FUNCIONÁRIO",
        FUN_TELEFONE AS "TELEFONE FUNCIONÁRIO",
        FUN_EMAIL AS "EMAIL FUNCIONÁRIO",
        "FUNCIONÁRIO" AS "TIPO"
FROM FUNCIONARIO
WHERE UPPER(FUN_EMAIL) LIKE "%%HOTMAIL%%"
OR UPPER(FUN_EMAIL) LIKE "%%OUTLOOK%%"
UNION
SELECT 	SUP_RAZAO_$OCIAL AS "RAZÃO SOCIAL",
		SUP_CNPJ AS "CPF/CNPJ SUPERMERCADO",
        SUP_TELEFONE AS "TELEFONE SUPERMERCADO",
        SUP_EMAIL AS "EMAIL SUPERMERCADO",
        "CONSUMIDOR" AS "TIPO"
FROM SUPERMERCADO
WHERE UPPER(SUP_EMAIL) LIKE "%%HOTMAIL%%"
OR UPPER(SUP_EMAIL) LIKE "%%OUTLOOK%%";
/*CROSS JOIN:
RETORNA TODOS OS PRODUTOS E OS SUPERMERCADOS EM QUE SÃO VENDIDOS*/
SELECT 	PRODUTO.PRO_NOME AS "NOME",
		PRODUTO.PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS",
		SUPERMERCADO.SUP_RAZAO_$OCIAL AS "RAZÃO SOCIAL"
FROM SUPERMERCADO_PRODUTO
CROSS JOIN SUPERMERCADO
CROSS JOIN PRODUTO
WHERE PRODUTO.PRO_ID=SUPERMERCADO_PRODUTO.FK_PRO_ID
AND SUPERMERCADO.SUP_CNPJ=SUPERMERCADO_PRODUTO.FK_SUP_CNPJ;
/*
SELECT TABELA.COLUNA
FROM TABELA
INNER '' OUTRA_TABELA(TABELA.COLUNA=OUTRA_TABELA_COLUNA)*/
/*INNER JOIN:
RETORNA APENAS OS PRODUTOS QUE FORAM COMPRADOS POR UM CONSUMIDOR*/
SELECT 	PRODUTO_CONSUMIDOR.PCO_ID AS "ID DA COMPRA",
		PRODUTO.PRO_NOME AS "NOME PRODUTO",
		PRODUTO.PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS",
		CONSUMIDOR.CON_NOME AS "NOME CONSUMIDOR",
        CONSUMIDOR.CON_CPF AS "CPF"
FROM PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID=PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF=CONSUMIDOR.CON_CPF);
/*EXERCÍCIO INNER JOIN
RETORNA O NOME DO SUPERMERCADO, O NOME DO FUNCIONÁRIO E EM QUE MERCADO ELE TRABALHA*/
SELECT SUPERMERCADO.SUP_RAZAO_$OCIAL 	AS "SUPERMERCADO",
		FUNCIONARIO.FUN_NOME 			AS "NOME"
FROM SUPERMERCADO
INNER JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ=FUNCIONARIO.FK_SUP_CNPJ);
/*RETORNAR NOME DO PRODUTO E O SUPERMERCADO EM QUE ELE ESTÁ DISPONÍVEL*/
SELECT 	PRODUTO.PRO_NOME 				AS "PRODUTO",
		SUPERMERCADO.SUP_RAZAO_$OCIAL 	AS "RAZÃO SOCIAL"
FROM SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO 		ON (PRODUTO.PRO_ID=SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ=SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);
/*LEFT JOIN*/
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME,PRO_PESO,PRO_QTD,PRO_PRECO,PRO_DATA_VALIDADE)
VALUE("123124","KITKAT","30","1500",4.5,"2026-01-01");
SELECT * FROM SUPERMERCADO;
INSERT INTO `bd_supermercado_funcionario_produto_consumidor`.`SUPERMERCADO` (`SUP_CNPJ`, `SUP_RAZAO_$OCIAL`, `SUP_TELEFONE`, `SUP_EMAIL`, `SUP_ENDERECO_LOGRADOURO`, `SUP_ENDERECO_NUMERO`, `SUP_ENDERECO_CIDADE`, `SUP_ENDERECO_ESTADO`) VALUES ('000000000', 'MERCADÃO CAZÉ', '(19)6969696', 'mercadãocazé@cazétv.com', 'Rua rua', '69', 'São Paulo', 'SP');
SELECT PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_$OCIAL
FROM PRODUTO
LEFT JOIN SUPERMERCADO_PRODUTO 	ON (PRODUTO.PRO_ID=SUPERMERCADO_PRODUTO.FK_PRO_ID)
LEFT JOIN SUPERMERCADO 			ON (SUPERMERCADO.SUP_CNPJ=SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);
SELECT PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_$OCIAL
FROM PRODUTO
RIGHT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID=SUPERMERCADO_PRODUTO.FK_PRO_ID)
RIGHT JOIN SUPERMERCADO 		ON (SUPERMERCADO.SUP_CNPJ=SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);
/*SELECT COM LEFT E RIGHT JOIN*/
SELECT *
FROM (
	SELECT 	S.SUP_RAZAO_$OCIAL 	AS RAZAO_SOCIAL,
			F.FUN_NOME 			AS NOME_FUNCIONARIO,
            P.PRO_NOME 			AS NOME_PRODUTO,
            C.CON_NOME 			AS NOME_CONSUMIDOR
	FROM SUPERMERCADO S
    LEFT JOIN FUNCIONARIO F 			ON (S.SUP_CNPJ=F.FK_SUP_CNPJ)
    LEFT JOIN SUPERMERCADO_PRODUTO SP 	ON (S.SUP_CNPJ=SP.FK_SUP_CNPJ)
    LEFT JOIN PRODUTO P 				ON (SP.FK_PRO_ID = P.PRO_ID)
    LEFT JOIN PRODUTO_CONSUMIDOR PC		ON (P.PRO_ID=PC.FK_PRO_ID)
    LEFT JOIN CONSUMIDOR C 				ON (PC.FK_CON_CPF=C.CON_CPF)
    UNION
    	SELECT 	S.SUP_RAZAO_$OCIAL 	AS RAZAO_SOCIAL,
			F.FUN_NOME 			AS NOME_FUNCIONARIO,
            P.PRO_NOME 			AS NOME_PRODUTO,
            C.CON_NOME 			AS NOME_CONSUMIDOR
	FROM SUPERMERCADO S
    RIGHT JOIN FUNCIONARIO F 			ON (S.SUP_CNPJ=F.FK_SUP_CNPJ)
    RIGHT JOIN SUPERMERCADO_PRODUTO SP 	ON (S.SUP_CNPJ=SP.FK_SUP_CNPJ)
    RIGHT JOIN PRODUTO P 				ON (SP.FK_PRO_ID = P.PRO_ID)
    RIGHT JOIN PRODUTO_CONSUMIDOR PC	ON (P.PRO_ID=PC.FK_PRO_ID)
    RIGHT JOIN CONSUMIDOR C 			ON (PC.FK_CON_CPF=C.CON_CPF)
) SELECT_EXTERNO
ORDER BY	SELECT_EXTERNO.RAZAO_SOCIAL ASC,
			SELECT_EXTERNO.NOME_FUNCIONARIO DESC,
            SELECT_EXTERNO.NOME_PRODUTO ASC,
            SELECT_EXTERNO.NOME_CONSUMIDOR DESC;
            
/*ex1*/
SELECT 	SUPERMERCADO.SUP_RAZAO_$OCIAL 	AS "RAZÃO SOCIAL",
		PRODUTO.PRO_NOME 				AS "PRODUTO"
FROM SUPERMERCADO_PRODUTO
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ=SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
INNER JOIN PRODUTO 		ON (PRODUTO.PRO_ID=SUPERMERCADO_PRODUTO.FK_PRO_ID);
SELECT 	FUNCIONARIO.FUN_NOME 			AS "FUNCIONÁRIO",
		SUPERMERCADO.SUP_RAZAO_$OCIAL 	AS "SUPERMERCADO"
FROM SUPERMERCADO
INNER JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ=FUNCIONARIO.FK_SUP_CNPJ);
SELECT 	CONSUMIDOR.CON_NOME AS "NOME CONSUMIDOR",
		PRODUTO.PRO_NOME AS "NOME PRODUTO"
FROM PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID=PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF=CONSUMIDOR.CON_CPF);
SELECT 	PRODUTO.PRO_NOME AS "NOME PRODUTO",
		CONSUMIDOR.CON_NOME AS "NOME CONSUMIDOR"
FROM PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID=PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF=CONSUMIDOR.CON_CPF);
SELECT 	SUPERMERCADO.SUP_RAZAO_$OCIAL 	AS "RAZÃO SOCIAL",
		COUNT(PRODUTO.PRO_ID) 			AS "QTD PRODUTOS"
FROM SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO 		ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
GROUP BY SUPERMERCADO.SUP_RAZAO_$OCIAL;

/*ex2*/
SELECT SUPERMERCADO.SUP_RAZAO_$OCIAL,
		PRODUTO.PRO_NOME
FROM SUPERMERCADO
LEFT JOIN SUPERMERCADO_PRODUTO 	ON (SUPERMERCADO.SUP_CNPJ=SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
LEFT JOIN PRODUTO 			ON (PRODUTO.PRO_ID=SUPERMERCADO_PRODUTO.FK_PRO_ID);

SELECT FUNCIONARIO.FUN_NOME,
		SUPERMERCADO.SUP_RAZAO_$OCIAL
FROM FUNCIONARIO
LEFT JOIN SUPERMERCADO 			ON (SUPERMERCADO.SUP_CNPJ=FUNCIONARIO.FK_SUP_CNPJ);

SELECT CONSUMIDOR.CON_NOME,
		PRODUTO.PRO_NOME
FROM CONSUMIDOR C
LEFT JOIN PRODUTO_CONSUMIDOR PC 	ON (C.CON_CPF=PC.FK_PRO_ID)
LEFT JOIN PRODUTO P 	ON (P.PRO_ID=PC.FK_PRO_ID);

SELECT 	P.PRO_NOME,
		C.CON_NOME
FROM PRODUTO P
LEFT JOIN PRODUTO_CONSUMIDOR PC 	ON (P.PRO_ID=PC.FK_PRO_ID)
LEFT JOIN CONSUMIDOR C 	ON (C.CON_CPF=PC.FK_CON_CPF);

SELECT SUPERMERCADO.SUP_RAZAO_$OCIAL,
		FUNCIONARIO.FUN_NOME
FROM SUPERMERCADO
LEFT JOIN FUNCIONARIO 	ON (SUPERMERCADO.SUP_CNPJ=FUNCIONARIO.FK_SUP_CNPJ);
/*ex3*/
SELECT P.PRO_NOME,
       S.SUP_RAZAO_$OCIAL
FROM SUPERMERCADO_PRODUTO SP
RIGHT JOIN PRODUTO P ON (P.PRO_ID = SP.FK_PRO_ID)
RIGHT JOIN SUPERMERCADO S ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ);

SELECT C.CON_NOME,
       P.PRO_NOME
FROM CONSUMIDOR C
RIGHT JOIN PRODUTO_CONSUMIDOR PC ON (C.CON_CPF = PC.FK_CON_CPF)
LEFT JOIN PRODUTO P ON (P.PRO_ID = PC.FK_PRO_ID);

SELECT F.FUN_NOME,
       S.SUP_RAZAO_$OCIAL
FROM FUNCIONARIO F
RIGHT JOIN SUPERMERCADO S ON (S.SUP_CNPJ = F.FK_SUP_CNPJ);

SELECT S.SUP_RAZAO_$OCIAL,
       P.PRO_NOME
FROM SUPERMERCADO S
RIGHT JOIN SUPERMERCADO_PRODUTO SP ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
RIGHT JOIN PRODUTO P ON (P.PRO_ID = SP.FK_PRO_ID);

SELECT C.CON_NOME,
       P.PRO_NOME
FROM PRODUTO_CONSUMIDOR PC
RIGHT JOIN CONSUMIDOR C ON (C.CON_CPF = PC.FK_CON_CPF)
RIGHT JOIN PRODUTO P ON (P.PRO_ID = PC.FK_PRO_ID);
/*SUBCONSULTAS*/
/*IN*/
/*REGISTRAR APENAS OS PRODUTOS DE UM SUPERMERCADO QUE POSSUEM REGISTRO EM UM SUPERMERCADO E QUE FORAM COMPRADOS POR UM CONSUMIDOR*/
SELECT 	PRODUTO.PRO_NOME 			AS "NOME PRODUTO",
		PRODUTO.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS", 
        PRODUTO.PRO_PRECO 		AS "PREÇO"
FROM PRODUTO
WHERE PRODUTO.PRO_ID IN (SELECT SUPERMERCADO_PRODUTO.FK_PRO_ID FROM SUPERMERCADO_PRODUTO)
AND PRODUTO.PRO_ID IN (SELECT PRODUTO_CONSUMIDOR.FK_PRO_ID FROM PRODUTO_CONSUMIDOR);
/*NOT IN*/
SELECT 	PRODUTO.PRO_NOME 			AS "NOME PRODUTO",
		PRODUTO.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS", 
        PRODUTO.PRO_PRECO 		AS "PREÇO"
FROM PRODUTO
WHERE PRODUTO.PRO_ID NOT IN (SELECT SUPERMERCADO_PRODUTO.FK_PRO_ID FROM SUPERMERCADO_PRODUTO)
AND PRODUTO.PRO_ID NOT IN (SELECT PRODUTO_CONSUMIDOR.FK_PRO_ID FROM PRODUTO_CONSUMIDOR);
/*ALL*/
/*SELECIONAR OS SUPERMERCADOS QUE TEM O PREÇO DE TODOS OS PRODUTOS MENORES QUE R$10,00*/
SELECT SUPERMERCADO.SUP_RAZAO_$OCIAL
FROM SUPERMERCADO
WHERE 10<ALL (SELECT PRODUTO.PRO_PRECO
				FROM PRODUTO);
/*ANY*/
/*LISTAR TODOS OS PRODUTOS CUJO PREÇO SEJA MAIOR QUE O PREÇO DE QUALQUER PRODUTO VENDIDO NO SUPERMERCADO COM O CNPJ: 2131212*/
SELECT PRO_NOME,
PRO_PRECO
FROM PRODUTO
WHERE PRO_PRECO>ANY(
	SELECT PRODUTO.PRO_PRECO
    FROM PRODUTO
    INNER JOIN SUPERMERCADO_PRODUTO
    ON (PRODUTO.PRO_ID-SUPERMERCADO_PRODUTO.FK_PRO_ID)
    WHERE SUPERMERCADO_PRODUTO.FK_SUP_CNPJ ="12.345.678"
);
/*EXISTS*/
/*LISTAR TODOS OS CONSUMIDORES QUE COMPRARAM PELO MENOS UM PRODUTO*/
SELECT CONSUMIDOR.CON_NOME,
CONSUMIDOR.CON_CPF
FROM CONSUMIDOR
WHERE EXISTS (
	SELECT 1
    FROM PRODUTO_CONSUMIDOR
    WHERE PRODUTO_CONSUMIDOR.FK_CON_CPF=CONSUMIDOR.CON_CPF
);
/*NOT EXISTS*/
SELECT CONSUMIDOR.CON_NOME,
CONSUMIDOR.CON_CPF
FROM CONSUMIDOR
WHERE NOT EXISTS (
	SELECT 1
    FROM PRODUTO_CONSUMIDOR
    WHERE PRODUTO_CONSUMIDOR.FK_CON_CPF=CONSUMIDOR.CON_CPF
);
/*TCL-LINGUAGEM DE CONTROLE DE TRANSAÇÕES:
ROLLBACK*/
-- 1°: INICIAR A TRANSAÇÃO
START TRANSACTION;
-- 2°: ESCREVER O COMANDO DML
INSERT INTO SUPERMERCADO (
SUP_CNPJ,
SUP_RAZAO_$OCIAL, 
SUP_TELEFONE,
SUP_EMAIL,
SUP_ENDERECO_LOGRADOURO,
SUP_ENDERECO_NUMERO,
SUP_ENDERECO_CIDADE,
SUP_ENDERECO_ESTADO)
VALUES ("10.70.303", 
		"MERCADO CAZE TV",
		"(69) 1234-4321",
		"MERCADO@CAZETV.com.br",
		"Casa do caralho",
		"69",
		"Broxópolis",
		"PN");
-- 3°: SE TUDO DER CERTO ENVIA PRO BANCO
COMMIT;
/*TCL-LINGUAGEM DE CONTROLE DE TRANSAÇÕES:
COMMIT*/
-- 1°: INICIAR A TRANSAÇÃO
START TRANSACTION;
-- 2°: ESCREVER O COMANDO DML
INSERT INTO SUPERMERCADO (
SUP_CNPJ,
SUP_RAZAO_$OCIAL, 
SUP_TELEFONE,
SUP_EMAIL,
SUP_ENDERECO_LOGRADOURO,
SUP_ENDERECO_NUMERO,
SUP_ENDERECO_CIDADE,
SUP_ENDERECO_ESTADO)
VALUES ("10.70.303", 
		"MERCADO CAZE TV",
		"(69) 1234-4321",
		"MERCADO@CAZETV.com.br",
		"Casa do caralho",
		"69",
		"Broxópolis",
		"PN");
-- 3°: SE TUDO DER CERTO ENVIA PRO BANCO
ROLLBACK;
-- SAVE POINT
START TRANSACTION;
INSERT INTO SUPERMERCADO (
SUP_CNPJ,
SUP_RAZAO_$OCIAL, 
SUP_TELEFONE,
SUP_EMAIL,
SUP_ENDERECO_LOGRADOURO,
SUP_ENDERECO_NUMERO,
SUP_ENDERECO_CIDADE,
SUP_ENDERECO_ESTADO)
VALUES ("10.70.301", 
		"MERCADO CAZE tv",
		"(69) 1234-4321",
		"MERCADO@CAZETV.com.br",
		"Casa do caralho",
		"69",
		"Broxópolis",
		"PN");
SAVEPOINT SAVEPOINT_PRODUTO1;
INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QTD,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES ("7891000051231",
		"PINTO DE BORRACHA",
		"250g",
		"690",
		15.50,
		"2026-02-21");
SAVEPOINT SAVEPOINT_PRODUTO2;
INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QTD,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES ("7891000051230",
		"PINTO DE METAL",
		"1000g",
		"24",
		24.24,
		"2026-02-24");
-- SE TIVER UM ERRO, REVERTER ATÉ O SAVE POINT 2
ROLLBACK TO SAVEPOINT_PRODUTO2;
-- CONFIRMAR SOMENTE O PRODUTO 1
COMMIT;

